config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root 'home#index', as: 'home'
  resources :posts, except: [:index]
  resources :comments, only: [:create, :destroy, :show]
  #profile
  get '/view/:id', to: 'profile#show', as: 'view_profile'
  get '/profile/edit', to: 'profile#edit'
  patch '/profile/update', to: 'profile#update'
  get '/view_all', to: 'profile#show_all'


   #likes
   post '/like/:post_id', to: 'likes#create', as: 'like'
   delete '/unlike/:post_id', to: 'likes#destroy', as: 'unlike'

  #followings
  get '/follows/:id', to: 'follows#show', as: 'follows'
  post '/follow/:id', to: 'follows#create', as: 'follow'
  delete '/unfollow/:id', to: 'follows#destroy', as: 'unfollow'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/follow.rb
class Follow < ApplicationRecord
  
  extend ActsAsFollower::FollowerLib
  extend ActsAsFollower::FollowScopes

  # NOTE: Follows belong to the "followable" and "follower" interface
  belongs_to :followable, polymorphic: true
  belongs_to :follower,   polymorphic: true

  def block!
    self.update_attribute(:blocked, true)
  end

end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/post.rb
class Post < ApplicationRecord
  validates :caption, presence: true
  
  belongs_to :user
  
  has_many :comments
  has_many :likes
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  
  
         has_many :posts
         has_one :profile
       
         has_many :comments
  
  
acts_as_followable
acts_as_follower
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :update_allowed_parameters, if: :devise_controller?

  protected

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :surname, :email, :password)}
    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :surname, :email, :password, :current_password)}
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @comment = Comment.new(text: params[:comment][:text], post_id: params[:post_id], user_id: current_user.id)
    respond_to do |format|
      format.js
    end
  end
end

app/controllers/follows_controller.rb
class FollowsController < ApplicationController
  before_action :authenticate_user!

  def show
    @user = User.find(params[:id])

    @following_count = @user.follow_count 
    @follower_count = @user.followers_count

    @followings = @user.all_following
    @followers = @user.followers
  end

  def create
    user = User.find(current_user.id)
    followed_user = User.find(params[:id])
    user.follow(followed_user)
    respond_to do |format|
      format.js
    end
  end

  def destroy
    user = User.find(current_user.id)
    followed_user = User.find(params[:id])
    user.stop_following(followed_user)
    respond_to do |format|
      format.js
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!
  def index
    #todo: show posts by following users here
    # @posts = Post.joins("INNER JOIN follows ON posts.user_id = follows.followable_id")
      # .where("follows.follower_id = ?", current_user.id).order('posts.updated_at').reverse_order

    #show profile
    @post = Post.all
    @profile = User.select(:handle, :name, :bio, 'profiles.id').joins(:profile).find_by('users.id' => current_user.id)
  end
end

app/controllers/like_controller.rb
class LikeController < ApplicationController
  def create
    @like = Like.new(post_id: params[:post_id], user_id: current_user.id)
    respond_to do |format|
      format.js
    end
  end

  def destroy
    @unlike = Like.find_by(post_id: params[:post_id])
    respond_to do |format|
      format.js
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!
  def new
  end

  def create
    @post = current_user.posts.new(caption: post_params[:caption])
    if @post.save
      redirect_to view_profile_path(current_user.id)
    else
      @errors = @post.errors.full_messages
      render :new
    end
  end

  def post_params
    params.require(:new_post).permit(:caption)
  end

  def edit
    @post = Post.find_by(id: params[:id])
  end

  def update
    @post = Post.find_by(id: params[:id])
    if @post.update(caption: params[:post][:caption])
      redirect_to view_profile_path(current_user.id)
    else
      render :edit     
    end
  end

  def destroy
    Post.destroy(params[:id])
    redirect_to view_profile_path(current_user.id)
  end
end

app/controllers/profile_controller.rb
class ProfileController < ApplicationController
  def show
    id = params[:id]

    @user = User.find(id)

    @following_count = @user.follow_count 
    @follower_count = @user.followers_count

    @profile = User.select(:handle, :name, :bio, 'profiles.id').joins(:profile).find_by('users.id' => id)

    @all_posts = Post.joins(:user).select(:id, :caption, :created_at, :updated_at, :user_id).where('users.id' => id).order('posts.updated_at').reverse_order

  end

  def update
    @pf = Profile.find_by(user_id: current_user.id)
    @pf.update(handle: pf_params[:handle], name: pf_params[:name], bio: pf_params[:bio])
    redirect_to view_profile_path(current_user.id)
  end

  def edit
    @profile = Profile.find_by(user_id: current_user.id)
  end

  def show_all
    @all_users = User.all    
  end

  protected
  def pf_params
    params.require(:profile).permit(:handle, :name, :bio,:user_name,:email,:deactivated)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/follows_helper.rb
module FollowsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/like_helper.rb
module LikeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/profile_helper.rb
module ProfileHelper
end

app/views/comments/create.js.erb
<% if @comment.save %>
  $('#comment-<%= @comment.post_id %>').append('<div><span class="font-weight-bold"><%= current_user.profile.handle %></span> <%= @comment.text %></div>');
  
<% end %>

app/views/follows/_follow_button.html.erb
<% if user_followed?(profile_id) %>
  <%= link_to unfollow_path(profile_id), method: :delete, remote: true do %>
    Unfollow
  <% end %>
<% else %>
  <%= link_to follow_path(profile_id), method: :post, remote: true do %>
    Follow
  <% end %>
<% end %>

app/views/follows/create.js.erb
$('#follow-btn').html('<%= link_to 'Unfollow', unfollow_path(), method: :delete, remote: true %>')

app/views/follows/destroy.js.erb
$('#follow-btn').html('<%= link_to 'Follow', follow_path(), method: :post, remote: true %>')

app/views/follows/show.html.erb
<div class="container">
  <%= link_to view_profile_path(current_user.id), method: :get do %>
    <div class="btn btn-sm btn-secondary">Back to profile</div>
  <% end %>
  <div>Following</div>
  <div class="list-group">
    <% @followings.each do |f| %>
      <li class="list-group-item">
        <%= link_to view_profile_path(f.id), method: :get do %>
          <div><%= f.profile.name %></div>
        <% end %>
      </li>
    <% end %>
  </div>
  <div>Followers</div>
  <div class="list-group">
    <% @followers.each do |f| %>
      <li class="list-group-item">
          <%= f.email %>
      </li>
    <% end %>
  </div>
</div>

app/views/home/index.html.erb
<div class="container">
  <%= link_to :new_post, method: :get do %>
    <div class="btn btn-secondary btn-sm">New Post</div>
  <% end %>

  <%= link_to :destroy_user_session, method: :delete do %>
    <div class="btn btn-secondary btn-sm">Log out</div>
  <% end %>

  <%= link_to view_profile_path(current_user.id), method: :get do %>
    <div class="btn btn-secondary btn-sm">Profile</div>
  <% end %>

  <%= link_to :view_all, method: :get do %>
    <div class="btn btn-secondary btn-sm">All profiles</div>
  <% end %>
</div>

<div class="container row">
<div class="col-lg-8">
  <% @post.each do |p| %>
    <div class="card post rounded-sm bg-white">
      <div class="card-header font-weight-bold">
        <%= link_to view_profile_path(p.user_id), method: :get do %>
          <%= p.user&.profile&.handle %>
        <% end %>
      </div>
      <img class="card-img-top" src="/insta-logo.png" alt="">
      <div class="card-body border-bottom">
        <div class="card-text">
          <div id="like-<%= p.id %>">
            <%= render "likes/like_button", post_id: p.id %>
          </div>
        </div>
        <div class="card-text">
          <span class="font-weight-bold"><%= p.user&.profile&.handle %></span> <%= p.caption %>
        </div>
        <div class="card-text" id="comment-<%= p.id %>">
          <% p.comments.each do |c| %>
            <div>
              <span class="font-weight-bold"><%= current_user.profile.handle %></span> <%= c.text %>
            </div>
          <% end %>
        </div>
        <h6 class="mb-2 text-muted">
          <% if p.created_at != nil %>
            <%= distance_of_time_in_words_to_now(p.created_at) %> ago
          <% end %>
        </h6>
      </div>
      <%= form_for :comment, url: comments_path(), remote: true, html: { class: 'input-group' } do |f| %>
        <%= f.text_field :text, placeholder: 'Add a comment...', class: 'form-control border-0' %>
        <%= hidden_field_tag :post_id, p.id %>
        <%= f.submit 'Post', class: 'btn' %>
      <% end %>
    </div>
  <% end %>
</div>

<div class="col-lg-4">
  <%= render 'profile/show_mini' %>
</div>
</div>

app/views/like/_like_button.html.erb
<% if Like.find_by(post_id: post_id).nil? %>
  <%= link_to like_path(post_id), method: :post, remote: true do %>like<% end %>
<% else %>
  <%= link_to unlike_path(post_id), method: :delete, remote: true do %>unlike<% end %>
<% end %>

app/views/likes/_like_button.html.erb
<% if Like.find_by(post_id: post_id).nil? %>
<%debugger%>
  <%= link_to like_path(post_id), method: :post, remote: true do %>like<% end %>
<% else %>
  <%= link_to unlike_path(post_id), method: :delete, remote: true do %>unlike<% end %>
<% end %>

app/views/likes/create.js.erb
<% if @like.save %>
  $('#like-<%= @like.post_id %>').html('<%= link_to unlike_path(), method: :delete, remote: true do %>unlike<% end %>');
<% end %>

app/views/likes/destroy.js.erb
<% if @unlike.destroy %>
  $('#like-<%= @unlike.post_id %>').html('<%= link_to like_path(), method: :post, remote: true do %>like<% end %>');
<% end %>

app/views/posts/edit.html.erb
<div class="container">
<% if !@errors.nil? %>
  <% @errors.each do |msg| %>
    <div class="alert alert-warning"><%= msg %></div>
  <% end %>
<% end %>
<%= form_for :new_post, url: posts_path do |f| %>  
  <div class="field">
    <%= f.text_area :caption, placeholder: true, class: 'form-control' %>
  </div>
  <div class="actions">
    <%= f.submit 'Post', class: 'btn btn-primary'%>
  </div>
<% end %>

</div>

app/views/posts/new.html.erb
<div class="container">
<% if !@errors.nil? %>
  <% @errors.each do |msg| %>
    <div class="alert alert-warning"><%= msg %></div>
  <% end %>
<% end %>
<%= form_for :new_post, url: posts_path do |f| %>  
  <div class="field">
    <%= f.text_area :caption, placeholder: true, class: 'form-control' %>
  </div>
  <div class="actions">
    <%= f.submit 'Post', class: 'btn btn-primary'%>
  </div>
<% end %>

</div>